devices:
  - name: switch-core-SUR
    type: switch                 # switch | router | server | firewall
    host: 172.16.0.1
    port: 161
    snmp_version: 2c
    community: Morelos
    timeout: 2
    retries: 1
    oids:
      - oid: 1.3.6.1.2.1.1.1.0
        label: Descripción
      - oid: 1.3.6.1.2.1.1.3.0
        label: Uptime
#      - oid: 1.3.6.1.2.1.2.1.0
#        label: Interfaces
      - oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8.19
        label: CPU 5min %
  - name: switch-core-NORTE
    type: switch                 # switch | router | server | firewall
    host: 172.16.0.5
    port: 161
    snmp_version: 2c
    community: Morelos
    timeout: 2
    retries: 1
    oids:
      - oid: 1.3.6.1.2.1.1.1.0
        label: Descripción
      - oid: 1.3.6.1.2.1.1.3.0
        label: Uptime
#      - oid: 1.3.6.1.2.1.2.1.0
#        label: Interfaces
      - oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8.1
        label: CPU 5min %
  - name: switch-core-APs
    type: switch                 # switch | router | server | firewall
    host: 172.16.0.86
    port: 161
    snmp_version: 2c
    community: Morelos
    timeout: 2
    retries: 1
    oids:
      - oid: 1.3.6.1.2.1.1.1.0
        label: Descripción
      - oid: 1.3.6.1.2.1.1.3.0
        label: Uptime
#      - oid: 1.3.6.1.2.1.2.1.0
#        label: Interfaces
      - oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8.1
        label: CPU 5min %
  - name: switch-core-ESTE
    type: switch                 # switch | router | server | firewall
    host: 172.16.0.3
    port: 161
    snmp_version: 2c
    community: Morelos
    timeout: 2
    retries: 1
    oids:
      - oid: 1.3.6.1.2.1.1.1.0
        label: Descripción
      - oid: 1.3.6.1.2.1.1.3.0
        label: Uptime
      - oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8.19
        label: CPU 5min %
      - oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8.20
        label: CPU 5min % (módulo 2)
  - name: switch-Merino
    type: switch                 # switch | router | server | firewall
    host: 172.16.0.86
    port: 161
    snmp_version: 2c
    community: Morelos
    timeout: 2
    retries: 1
    oids:
      - oid: 1.3.6.1.2.1.1.1.0
        label: Descripción
      - oid: 1.3.6.1.2.1.1.3.0
        label: Uptime
#      - oid: 1.3.6.1.2.1.2.1.0
#        label: Interfaces
      - oid: 1.3.6.1.4.1.9.9.109.1.1.1.1.8.1
        label: CPU 5min %

#      - oid: 1.3.6.1.2.1.2.1.0
#        label: Interfaces

  # Ejemplo dispositivo SNMP v3 (credenciales desde variables de entorno)
#  - name: router-borde
#    type: router
#    host: 192.168.1.2
#    port: 161
#    snmp_version: 3
#    timeout: 2
#    retries: 1
#    oids:
#      - oid: 1.3.6.1.2.1.1.1.0
#        label: Descripción
#      - oid: 1.3.6.1.2.1.2.2.1.10.1
#        label: tráfico entrada iface 1
#      - oid: 1.3.6.1.2.1.2.2.1.16.1
#        label: tráfico salida iface 1
